version: "3.9"
services:
  bot:
    container_name: hummingbot
    image: hummingbot/hummingbot:latest
    volumes:
      - "./hummingbot_files/conf:/home/hummingbot/conf"
      - "./hummingbot_files/conf/connectors:/home/hummingbot/conf/connectors"
      - "./hummingbot_files/conf/strategies:/home/hummingbot/conf/strategies"
      - "./hummingbot_files/logs:/home/hummingbot/logs"
      - "./hummingbot_files/data:/home/hummingbot/data"
      - "./hummingbot_files/scripts:/home/hummingbot/scripts"
      - "./hummingbot_files/certs:/home/hummingbot/certs"
      - "./hummingbot_files/hummingbot/strategy:/home/hummingbot/hummingbot/strategy"
      - "./hummingbot_files/hummingbot/templates:/home/hummingbot/hummingbot/templates"
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: 5
    tty: true
    stdin_open: true
    network_mode: host
  # bot2:
  #   container_name: hummingbot_liquidity_mining
  #   image: hummingbot/hummingbot:latest
  #   volumes:
  #     - "./hummingbot_files/conf:/home/hummingbot/conf"
  #     - "./hummingbot_files/conf/connectors:/home/hummingbot/conf/connectors"
  #     - "./hummingbot_files/conf/strategies:/home/hummingbot/conf/strategies"
  #     - "./hummingbot_files/logs:/home/hummingbot/logs"
  #     - "./hummingbot_files/data:/home/hummingbot/data"
  #     - "./hummingbot_files/scripts:/home/hummingbot/scripts"
  #     - "./hummingbot_files/certs:/home/hummingbot/certs"
  #     - "./hummingbot_files/hummingbot:/home/hummingbot/hummingbot"
  #   logging:
  #     driver: "json-file"
  #     options:
  #         max-size: "10m"
  #         max-file: 5
  #   tty: true
  #   stdin_open: true
  #   network_mode: host
  dashboard:
    container_name: dashboard
    image: hummingbot/dashboard:latest
    volumes:
      - ./hummingbot_files/data:/home/dashboard/data
    ports:
      - "8501:8501"
